#Importing Numpy & Array creation

In [7]:
import numpy as np
print("Numpy Version",np.__version__)
arr = np.array([8,6,0,4,2])
print(arr)


Numpy Version 2.0.2
[8 6 0 4 2]


#Type Method (return type of  data)

In [8]:
print("Typ of array",type(arr))
print("Typ of array",arr.dtype)
d0= np.array(23)
print("Typ of array",d0.dtype)
fruit_list=["Apple","Mango","Banana"]
print("Typ of array",type(fruit_list))
fruit_list=np.array(fruit_list)
print("Typ of array",type(fruit_list))

Typ of array <class 'numpy.ndarray'>
Typ of array int64
Typ of array int64
Typ of array <class 'list'>
Typ of array <class 'numpy.ndarray'>


# Dimensions in Arrays

In [13]:

A = np.array([8,4,6,0,2])
print (A)
A_dimensions=A.ndim
print("A_dimensions",A_dimensions)
B=np.array([[8,4,6],[0,2,4]])
print (B)
B_dimensions=B.ndim
print("B_dimensions",B_dimensions)
C=np.array([[[8,4,6],[0,2,4],[1,3,5]]])
print (C)
C_dimensions=C.ndim
print("C_dimensions",C_dimensions)

[8 4 6 0 2]
A_dimensions 1
[[8 4 6]
 [0 2 4]]
B_dimensions 2
[[[8 4 6]
  [0 2 4]
  [1 3 5]]]
C_dimensions 3


# Dimensions through ndim


In [15]:
d1 = np.array(23, ndmin=5)
print("The array is of dimension: ", d1.ndim)
print("Elements of array d1 are",d1)
d2 = np.array([[8,4,6],[0,2,4],[9,6,7]])
print("The array is of dimension: ", d2.ndim)
print("Elements of array d2 are",d2)
print("Element at (1,0) row 1 column 0 is",d2[1,0])

The array is of dimension:  5
Elements of array d1 are [[[[[23]]]]]
The array is of dimension:  2
Elements of array d2 are [[8 4 6]
 [0 2 4]
 [9 6 7]]
Element at (1,0) row 1 column 0 is 0


# Depth of array

In [21]:
d3array =np.array([ [[1,3,3],[4,5,7],],[[4,7,8],[10,17,19],],[[13,18,20],[10,16,30]]])
print("The array is of dimension: ", d3array)
item = d3array[2][0][0]
print("Element at (1,2,0) is",d3array[2][0][0])


The array is of dimension:  [[[ 1  3  3]
  [ 4  5  7]]

 [[ 4  7  8]
  [10 17 19]]

 [[13 18 20]
  [10 16 30]]]
Element at (1,2,0) is 13


# Silicing 2-D Arrays

In [22]:
# Numpy array slicing
d1 = np.array([6, 8, 1, 2, 54, 5, 3])
print("Elements of array d1 are ", d1)

print("Elements slicing 'd1[1:5]' ", d1[1:5])
print("Elements slicing 'd1[:3]' ", d1[:3])
print("Elements slicing 'd1[3:]' ", d1[3:])
print("Elements slicing 'd1[-3:-1]' ", d1[-3:-1])

d2 = np.array([[5, 9, 3, 4], [21, 65, 8, 99], [56, 98, 1, 2]])
print("Elements of array d2 are ", d2)

print("Elements slicing 'd2[0, 1:3]' ", d2[0, 1:3])

Elements of array d1 are  [ 6  8  1  2 54  5  3]
Elements slicing 'd1[1:5]'  [ 8  1  2 54]
Elements slicing 'd1[:3]'  [6 8 1]
Elements slicing 'd1[3:]'  [ 2 54  5  3]
Elements slicing 'd1[-3:-1]'  [54  5]
Elements of array d2 are  [[ 5  9  3  4]
 [21 65  8 99]
 [56 98  1  2]]
Elements slicing 'd2[0, 1:3]'  [9 3]


In [23]:
print ("Array d1 sciling with step:d1[1:6:2] ",d1[1:6:2])

Array d1 sciling with step:d1[1:6:2]  [8 2 5]


# Numpy array shape


In [24]:
a2 = np.array([[11, 22, 33, 44], [14, 15, 16, 17]]) # Create a NumPy 2D-array
a2shape = a2.shape # Get the shape of the array
print("Shape of the array:", a2shape)

Shape of the array: (2, 4)


# Flatten Array

In [ ]:
a2D = np.array([[1, 2], [3, 4]])
print("Array a2D", a2D)
a2D.reshape(-1)

# NumPy Array Copy vs View


In [25]:

a = np.array([1, 2, 3, 4, 5, 6])
print("Array a",a)
b = a[:2]
print("Array b",b)
b += 1
print("Array b after increment if a",b)
print('Array a =', a, '; array b =', b)

#create a new array, using numpy.copy array
a = np.array([1, 2, 3, 4])
b = a[:2].copy()
b += 1
print('a = ', a, 'b = ', b)

Array a [1 2 3 4 5 6]
Array b [1 2]
Array b after increment if a [2 3]
Array a = [2 3 3 4 5 6] ; array b = [2 3]
a =  [1 2 3 4] b =  [2 3]


# NumPy Array Iteration

In [26]:
d1 = np.array([6,8,1,2,54,5,3])
for x in d1:
    print(x)

6
8
1
2
54
5
3


In [27]:
d2 = np.array([[58,69,34,45],[25,65,68,99],[56,98,1,2]]) #2-D Array
print("Elements of array d2 are ",d2)
for x in d2:
    for i in x:
        print(i)

Elements of array d2 are  [[58 69 34 45]
 [25 65 68 99]
 [56 98  1  2]]
58
69
34
45
25
65
68
99
56
98
1
2


In [28]:
d3 = np.array(np.array( [
    [[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]],
    [[13, 14, 15],[16, 17, 18]]]))
print("The dimension of array d3 is ",d3.ndim)
print(d3)
for x in d3:
    for y in x:
        for z in y:
            print(z)

The dimension of array d3 is  3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18


# Iterating Array using nditer()

In [29]:
d2 = np.array([[58,69,34,45],[25,65,68,99],[56,98,1,2]]) #2-D Array
print("Elements of array d2 are ",d2)
for x in np.nditer(d2):
    print(x)

Elements of array d2 are  [[58 69 34 45]
 [25 65 68 99]
 [56 98  1  2]]
58
69
34
45
25
65
68
99
56
98
1
2


# Numpy joining array


In [31]:
arr1 = np.array([1,2,3,4,5,6])
print("Array 1: ",arr1)
arr2 = np.array([7,8,9,10,11,12])
print("Array 2: ",arr2)
arr3 = np.concatenate((arr1,arr2))
print ("Concatenated array: arr3",arr3)

Array 1:  [1 2 3 4 5 6]
Array 2:  [ 7  8  9 10 11 12]
Concatenated array: arr3 [ 1  2  3  4  5  6  7  8  9 10 11 12]


# Joining arrays using Stack method


In [32]:
arr1 = np.array([1,2,3])
print("Array 1: ",arr1)
arr2 = np.array([7,8,9])
print("Array 2: ",arr2)
arr3 = np.stack((arr1,arr2), axis=1)
print ("Concatenated array through stack: arr3",arr3)

Array 1:  [1 2 3]
Array 2:  [7 8 9]
Concatenated array through stack: arr3 [[1 7]
 [2 8]
 [3 9]]


#NumPy Splitting Array

In [33]:
arr1 = np.array([1,2,3,4,5,6])
splitarr = np.array_split(arr1,3)
print("Array 1 split into 3 arrays",splitarr)
print("Array 1",splitarr[0])
print("Array 2",splitarr[1])
print("Array 3",splitarr[2])

Array 1 split into 3 arrays [array([1, 2]), array([3, 4]), array([5, 6])]
Array 1 [1 2]
Array 2 [3 4]
Array 3 [5 6]


# NumPy Searching Arrays

In [34]:
arr1 = np.array([1,2,3,4,5,6])
x = np.where(arr1 == 4)
print("Search index of 4",x)

Search index of 4 (array([3]),)


#Sorting : Search Sorted

In [35]:
arr2 = np.array([3,4,5,6,7,8])
x = np.searchsorted(arr2, 6)
print("Index of 6 is", x)

Index of 6 is 3


# NumPy Sorting Arrays

In [36]:
arr2 = np.array([3, 4, 5, 6, 7, 8])
x = np.searchsorted(arr2, 6)
print("Index of 6 is", x)

alparr = np.array(["Cherry", "Sugar", "Floor", "Cooking Oil"])
print(alparr)
print("Sorted array", np.sort(alparr))

Index of 6 is 3
['Cherry' 'Sugar' 'Floor' 'Cooking Oil']
Sorted array ['Cherry' 'Cooking Oil' 'Floor' 'Sugar']


#Filtering Arrays

In [37]:
arr = np.array([[58, 69, 34, 45], [25, 65, 68, 99], [56, 98, 1, 2]])
mask = arr > 45
new_array = arr[mask]
print(new_array)

[58 69 65 68 99 56 98]


# Task

In [38]:
import numpy as np

# Create a 3x3 matrix with values from 2 to 10
matrix = np.arange(2, 11).reshape(3, 3).astype(float)

print("Matrix:")
print(matrix)

# Flatten the matrix
flattened = matrix.flatten()

# Find maximum and minimum
max_value = flattened.max()
min_value = flattened.min()

print("\nFlattened array:")
print(flattened)
print("\nMaximum value:", max_value)
print("Minimum value:", min_value)


Matrix:
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]

Flattened array:
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]

Maximum value: 10.0
Minimum value: 2.0
